version: '3'

services:
  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: "elasticsearch"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    restart: on-failure
    volumes:
      - elastic:/var/lib/elasticsearch/data
  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"
    command: consul agent -server -bootstrap-expect=1 -ui -data-dir /consul/data -client=0.0.0.0
    restart: on-failure
  postgresql:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
  elastic:
    driver: local
